/**
 * The validation report.
 *
 * Ten deterministic checks, how many items each passed, and which check
 * rejected each dropped item. No model takes part in any of it — that
 * separation is the interesting claim, so the report states it plainly.
 */
import { Check, X } from 'lucide-react'

import { Badge, Card } from '../common'
import { checkLabel } from '../../lib/format'
import type { GenerationSummary, Question } from '../../lib/types'

function CheckRow({
  name,
  passed,
  failed,
}: {
  name: string
  passed: number
  failed: number
}) {
  const clean = failed === 0
  return (
    <tr className="border-b border-rule-2">
      <td className="py-1.5 pr-3">
        <span className="inline-flex items-center gap-2 text-13 text-ink">
          {clean ? (
            <Check size={14} strokeWidth={2} className="text-met" aria-hidden />
          ) : (
            <X size={14} strokeWidth={2} className="text-critical" aria-hidden />
          )}
          {checkLabel(name)}
        </span>
      </td>
      <td className="py-1.5 px-2 text-right font-mono text-13 tabular text-ink">{passed}</td>
      <td className="py-1.5 pl-2 text-right font-mono text-13 tabular">
        <span className={failed > 0 ? 'text-critical' : 'text-ink-3'}>{failed}</span>
      </td>
    </tr>
  )
}

export function ValidationReport({ summary }: { summary: GenerationSummary }) {
  const names = Array.from(
    new Set([...Object.keys(summary.check_pass_counts), ...Object.keys(summary.rejection_reasons)]),
  ).sort()

  return (
    <Card label="Validation report — deterministic, no model involved">
      <p className="mb-4 text-14 text-ink">
        <span className="font-mono font-medium tabular">{summary.generated}</span> generated,{' '}
        <span className="font-mono font-medium tabular text-met">{summary.passed}</span> passed,{' '}
        <span className="font-mono font-medium tabular text-critical">{summary.rejected}</span>{' '}
        rejected
        {summary.retried > 0 && (
          <>
            {' '}
            · <span className="font-mono tabular">{summary.retried}</span> chunk
            {summary.retried === 1 ? '' : 's'} retried once
          </>
        )}
        {' '}· across <span className="font-mono tabular">{summary.chunks_used}</span> source chunk
        {summary.chunks_used === 1 ? '' : 's'}
      </p>

      {summary.note && (
        <p className="mb-4 rounded border border-emerging/30 bg-emerging-bg px-3 py-2 text-13 text-emerging">
          {summary.note}
        </p>
      )}

      {names.length > 0 && (
        <div className="overflow-x-auto">
          <table className="w-full border-collapse">
            <thead>
              <tr className="border-b border-rule bg-surface-2">
                <th scope="col" className="py-2 pr-3 text-left font-mono text-11 uppercase tracking-[0.06em] text-ink-2">
                  Check
                </th>
                <th scope="col" className="py-2 px-2 text-right font-mono text-11 uppercase tracking-[0.06em] text-ink-2">
                  Passed
                </th>
                <th scope="col" className="py-2 pl-2 text-right font-mono text-11 uppercase tracking-[0.06em] text-ink-2">
                  Rejected
                </th>
              </tr>
            </thead>
            <tbody>
              {names.map((name) => (
                <CheckRow
                  key={name}
                  name={name}
                  passed={summary.check_pass_counts[name] ?? 0}
                  failed={summary.rejection_reasons[name] ?? 0}
                />
              ))}
            </tbody>
          </table>
        </div>
      )}

      {summary.rejected_questions.length > 0 && (
        <div className="mt-5">
          <p className="eyebrow mb-2">Rejected items</p>
          <ul className="space-y-2">
            {summary.rejected_questions.map((question) => (
              <RejectedItem key={question.id} question={question} />
            ))}
          </ul>
        </div>
      )}

      {summary.model && (
        <p className="mt-4 font-mono text-11 text-ink-3">
          generated by {summary.model} with a strict JSON schema · validated by rules
        </p>
      )}
    </Card>
  )
}

function RejectedItem({ question }: { question: Question }) {
  const failed = question.validation?.failed_checks ?? []
  return (
    <li className="rounded border border-rule bg-surface-2 p-3">
      <p className="text-13 leading-relaxed text-ink-2">{question.question_text}</p>
      <div className="mt-2 flex flex-wrap gap-1.5">
        {failed.map((name) => (
          <Badge key={name} tone="critical">
            {checkLabel(name)}
          </Badge>
        ))}
      </div>
      {failed.length > 0 && question.validation?.checks[failed[0]!]?.detail && (
        <p className="mt-1.5 font-mono text-11 text-ink-3">
          {question.validation.checks[failed[0]!]?.detail}
        </p>
      )}
    </li>
  )
}
